# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-07 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_provinsi', models.CharField(max_length=5)),
                ('province_name', models.CharField(max_length=200)),
                ('logo_provinsi', models.FileField(upload_to='')),
            ],
        ),
    ]
